services:
    backend: 
        build:
            args: 
                profile: azure
                port: 8080
        image: kinich49/item-tracker-backend:latest-azure
        ports:
            - "8080:8080"
    frontend:
        build:
            args:
                port: 80
        image: kinich49/item-tracker-frontend:latest-azure
        ports: 
            - "80:80"
        command: "80"