services:
    backend: 
        build:
            args: 
                profile: azure
                port: 8081
        image: kinich49/item-tracker-backend:latest-azure
        ports:
            - "8081:8081"
    frontend:
        build:
            args:
                port: 8080
        image: kinich49/item-tracker-frontend:latest-azure
        ports: 
            - "8080:8080"