services:
    backend: 
        build:
            args: 
                profile: development
                port: 9001
        image: item-tracker-development:backend
        ports:
            - "9001:9001"
    frontend:
        build:
            args:
                port: 4201
        image: item-tracker-development:frontend
        ports:
            - "4201:4201"
