version: '3.4'
services:
    backend: 
        build:
            dockerfile: Dockerfile
            context: ../item-tracker-rest
    frontend:
        build:
            dockerfile: Dockerfile
            context: ../item-tracker-vue
        depends_on:
            - backend
