name: Continous Delivery

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  continous_delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD 
        uses: actions/checkout@v2
              
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: kinich49/item-tracker-rest 
          path: item-tracker-rest

      - name: Move backend folder
        run: mv item-tracker-rest ..
          
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: kinich49/item-tracker-vue 
          path: item-tracker-vue
      
      - name: Move frontend folder
        run: mv item-tracker-vue ..

      - name: Build PROD
        run: docker-compose -f docker-compose.yml -f production.yml build  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push backend
        run: docker push kinich49/item-tracker:backend
      
      - name: Push frontend
        run: docker push kinich49/item-tracker:frontend
