# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow by an external source
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  continouts_integration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout CD 
        uses: actions/checkout@v2
              
      - name: Checkout backend
        uses: actions/checkout@v2
        with:
          repository: kinich49/item-tracker-rest 
          path: item-tracker-rest

      - name: Move backend folder
        run: mv item-tracker-rest ..
          
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: kinich49/item-tracker-vue 
          path: item-tracker-vue
      
      - name: Move frontend folder
        run: mv item-tracker-vue ..

      - name: Build PROD
        run: docker-compose -f docker-compose.yml -f production.yml build  

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push backend
        run: docker push kinich49/item-tracker:backend
      
      - name: Push frontend
        run: docker push kinich49/item-tracker:frontend
